const ActionTypes = {

    // Authentication Actions
    SET_PASSCODE: "SET_PASSCODE",
    CHECK_PASSCODE: "CHECK_PASSCODE",

    INCREMENT_PASSCODE_ATTEMPTS: "INCREMENT_PASSCODE_ATTEMPTS",
    CHANGE_AUTH_PREFERENCES: "CHANGE_AUTH_PREFERENCES",

    SEND_SECURITY_QUESTIONS_REQUEST: "SEND_SECURITY_QUESTIONS_REQUEST",
    RECEIVE_SECURITY_QUESTIONS_RESPONSE: "RECEIVE_SECURITY_QUESTIONS_RESPONSE",

    SEND_SECURITY_ANSWERS_REQUEST: "SEND_SECURITY_ANSWERS_REQUEST",
    RECEIVE_SECURITY_ANSWERS_RESPONSE: "RECEIVE_SECURITY_ANSWERS_RESPONSE", // Returns a authorization-code that must be sent with the activation request

    // Transaction Actions
    SEND_REFRESH_BALANCES_REQUEST: "SEND_REFRESH_BALANCES_REQUEST",
    RECEIVE_REFRESH_BALANCES_RESPONSE: "RECEIVE_REFRESH_BALANCES_RESPONSE",

    SEND_REFRESH_MICROS_REQUEST: "SEND_REFRESH_MICROS_REQUEST",
    RECEIVE_REFRESH_MICROS_RESPONSE: "RECEIVE_REFRESH_MICROS_RESPONSE",
    INVALIDATE_MICRO: "INVALIDATE_MICRO",

    // Search Vouchers Actions
    SEND_SEARCH_VOUCHERS_REQUEST: "SEND_SEARCH_VOUCHERS_REQUEST",
    RECEIVE_SEARCH_VOUCHERS_RESPONSE: "RECEIVE_SEARCH_VOUCHERS_RESPONSE",

    // Topup Actions
    ADD_VOUCHER_TO_CART: "ADD_VOUCHER_TO_CART",
    SEND_GENERATE_PAYMENT_URL_REQUEST: "SEND_GENERATE_PAYMENT_URL_REQUEST",
    RECEIVE_GENERATE_PAYMENT_URL_RESPONSE: "RECEIVE_GENERATE_PAYMENT_URL_RESPONSE",

    // Search Transactions Actions
    SEND_SEARCH_TRANSACTIONS_REQUEST: "SEND_SEARCH_TRANSACTIONS_REQUEST",
    RECEIVE_SEARCH_TRANSACTIONS_RESPONSE: "RECEIVE_SEARCH_TRANSACTIONS_RESPONSE",

    // Invite Users Actions
    SEND_INVITE_USERS_REQUEST: "SEND_INVITE_USERS_REQUEST",
    RECEIVE_INVITE_USERS_RESPONSE: "RECEIVE_INVITE_USERS_RESPONSE",

    // Free Credit Actions
    SEND_CLAIM_FREE_CREDIT_REQUEST: "SEND_CLAIM_FREE_CREDIT_REQUEST",
    RECEIVE_CLAIM_FREE_CREDIT_RESPONSE: "RECEIVE_CLAIM_FREE_CREDIT_RESPONSE",
    SET_FREE_CREDIT_WALKTHROUGH_INDEX: "SET_FREE_CREDIT_WALKTHROUGH_INDEX"

};
export default ActionTypes;