# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'micropay' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for micropay
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'

  

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'micropayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'micropay-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for micropay-tvOS

  target 'micropay-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
